[tool.poetry]
name = "python-redsys"
version = "0.3.0"
description = "A simple, clean and less dependant client to handle payments through Redsys."
authors = ["Andrés Reverón Molina <andres@reveronmolina.me>", "David Díaz <d.diazp@gmail.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/systemallica/python-redsys"
classifiers = [
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
]

[tool.poetry.dependencies]
python = "^3.9"
pycrypto = "^2.6.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
